name: Unit_Test
on: push
jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:        
      - uses: actions/checkout@v2
      - name: Gtest CMake
        run: cd /usr/src/gtest && cmake CMakeLists.txt && make
      - name: Symbolic links
        run: ln -st /usr/lib/ /usr/src/gtest/libgtest.a && ln -st /usr/lib/ /usr/src/gtest/libgtest_main.a
      - name: Build tests
        run: make unittest-build
      - name: Run test
        run: make unittest-run
