name: Basic_IOtest

on:
  push


jobs:
  
  build_and_test:

    runs-on: ubuntu-latest

   
    steps:
      
      - uses: actions/checkout@v2
        
      - name: Build
        run: g++ -Wall -Werror -std=c++17 *.cpp -o project
      - name: Make executeable
        run: chmod +x ./tests/IOtest.sh
      - name: generate files        
        run: ./tests/IOtest.sh 
      - name: I/O test 
        run: diff --strip-trailing-cr tests/output.csv tests/testfile_output.csv
